# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5ef6a643c9ab04453cc3a3162c8213457ebb636e088e67a458bd17e986a32f576f693679e4f9fc51cb1281f92fc3aba9a350e287075835c279c6eda16f1ae2d3

test:
  secret_key_base: 1ec9ba6c846d32a389a54f7238db36f13143ad240f3116de7922a8acaa32d91e537d4f5eec88957a66e3c26ec561018844a3aa07e7fe75b5f4397098fc1bb142

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
